// pipeline {
//     agent { docker 'python:3.9.5' }
//     stages {
//         stage('build') {
//             steps {
//                 bat 'python --version'
//             }
//         }
//     }
// }
pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat 'set'
                bat 'pip install -r requirements.txt || python setup.py install'
            }
        }
        stage('Test') {
            steps {
                bat 'echo %ComputerName%'
            }
        }
        stage('Deliver') { 
            steps {
                bat 'cd C:\\Users\\JWang294\\src\\cis\\libcalc\\auto_report_pipeline1.1 && python C:\\Users\\JWang294\\src\\cis\\libcalc\\auto_report_pipeline1.1\\test_automation\\main.py' 
            }
        }
    }
}
// pipeline {
//     agent any
//     stages {
//         stage('Build') {
//             steps {
//                 bat 'echo "Hello World"'
//                 bat '''
//                     echo "Multiline shell steps works too"
//                     ls -lah
//                 '''
//             }
//         }
//     }
// }
// pipeline {
//     agent any
//     stages {
//         stage('Test') {
//             steps {
//                 bat 'echo "Fail!"; exit 1'
//             }
//         }
//     }
//     post {
//         always {
//             echo 'This will always run'
//         }
//         success {
//             echo 'This will run only if successful'
//         }
//         failure {
//             echo 'This will run only if failed'
//         }
//         unstable {
//             echo 'This will run only if the run was marked as unstable'
//         }
//         changed {
//             echo 'This will run only if the state of the Pipeline has changed'
//             echo 'For example, if the Pipeline was previously failing but is now successful'
//         }
//     }
// }